version: "3"
services:
  app:
    image: node:18
    volumes:
      - ./:/app
      - ./package.json:/app/package.json
    working_dir: /app
    command: npm start
    environment:
      - NODE_ENV=development
